CREATE TABLE models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_name TEXT NOT NULL,
  openrouter_id TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT false
);

-- Turn on Row Level Security (RLS)
ALTER TABLE models ENABLE ROW LEVEL SECURITY;

-- Allow anonymous and authenticated read access
CREATE POLICY "Allow public read access to active models." ON models
  FOR SELECT USING (true);

-- Allow authenticated/anon updates (so clicking the UI toggles the row)
CREATE POLICY "Allow updates to toggle is_active." ON models
  FOR UPDATE USING (true) WITH CHECK (true);

-- Enable Realtime for the modes table by publishing all events to public schema:
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table models;

-- Seed initial models
INSERT INTO models (model_name, openrouter_id, is_active)
VALUES
  ('Anthropic Claude 3.5 Sonnet', 'anthropic/claude-3.5-sonnet', true),
  ('Google Gemini 3.1 Pro', 'google/gemini-3.1-pro:preview', false),
  ('Meta Llama 3 70B', 'meta-llama/llama-3-70b-instruct', false);
